[theme]
primaryColor = "#4A90E2"
backgroundColor = "#F0F2F5"
secondaryBackgroundColor = "#DDE1E7"
textColor = "#333333"
font = "sans serif"

[server]
port = 8502
enableStaticServing = true

[browser]
gatherUsageStats = false
